# Generated by Django 2.0.7 on 2018-07-30 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(max_length=200)),
                ('rus_word', models.CharField(max_length=200)),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('sound_url', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WordDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_learned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Word')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='users',
            field=models.ManyToManyField(through='dictionaries.WordStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='word_dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.WordDictionary'),
        ),
    ]
