# Generated by Django 2.0.7 on 2018-07-31 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='rus_word',
            new_name='ua_word',
        ),
    ]
